"""create core tables

Revision ID: acd71dac69e0
Revises: 
Create Date: 2026-01-05 02:38:35.103562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd71dac69e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_id')
    )
    op.create_index('ix_payouts_restaurant_currency', 'payouts', ['restaurant_id', 'currency'], unique=False)
    op.create_table('processor_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_processor_events_event_id')
    )
    op.create_index('ix_processor_events_restaurant_currency', 'processor_events', ['restaurant_id', 'currency'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('processor_event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['processor_event_id'], ['processor_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_restaurant_currency', 'ledger_entries', ['restaurant_id', 'currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_restaurant_currency', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_processor_events_restaurant_currency', table_name='processor_events')
    op.drop_table('processor_events')
    op.drop_index('ix_payouts_restaurant_currency', table_name='payouts')
    op.drop_table('payouts')
    # ### end Alembic commands ###
